# -*- coding: utf-8 -*-
"""App buat flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ihRsNA3r7O9GwYu_-rmip5k-8XH1Mjh4
"""

import tensorflow as tf
import numpy as np
from keras.preprocessing import image
from extracted_face import extract_face

model = tf.keras.models.load_model('/content/my_model.h5')

path = '/content/drive/MyDrive/Face Dataset/Train/C1151466/IMG_20210521_095254.jpg'
img = extract_face(path)
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)

images = np.vstack([x])
predictions = model.predict(images/255.0)
score = tf.nn.softmax(predictions[0])
print(predictions[0])